export const LISTA_ESCRITORIO = [
  { id: 55222, nome: 'ALMOFADA PARA CARIMBO – PRETA', unidade: 'UND' },
  { id: 51754, nome: 'ALMOFADA PARA CARIMBO – VERMELHA', unidade: 'UND' },
  { id: 865, nome: 'APAGADOR PARA LOUSA BRANCA', unidade: 'UND' },
  { id: 55217, nome: 'APONTADOR DE PLÁSTICO', unidade: 'UND' },
  { id: 52202, nome: 'BATERIA LITIO CR2023 3V: FORMATO: BOTÃO', unidade: 'UND' },
  { id: 52203, nome: 'BATERIA LITIO LR41: VOLTAGEM: 1,5V, FORMATO: BOTÃO', unidade: 'UND' },
  { id: 52193, nome: 'BLOCO AUTO ADESIVO – GRANDE: COM 45 FOLHAS', unidade: 'UND' },
  { id: 52194, nome: 'BLOCO AUTO ADESIVO – PEQUENO: 4 BLOCOS COM 50 FOLHAS', unidade: 'UND' },
  { id: 52208, nome: 'BOBINA PARA RELOGIO DE PONTO', unidade: 'UND' },
  { id: 55218, nome: 'BORRACHA BRANCA', unidade: 'UND' },
  { id: 55233, nome: 'CADERNO ESPIRAL 1/4: CAPA DURA, 96 FOLHAS, LISO', unidade: 'UND' },
  { id: 55234, nome: 'CADERNO ESPIRAL UNIVERSITÁRIO: GALVANIZADO, CAPA DURA, C/ 200 FLS', unidade: 'UND' },
  { id: 55239, nome: 'CAIXA PARA ARQUIVO MORTO AZUL', unidade: 'UND' },
  { id: 52204, nome: 'CALCULADORA DE MESA', unidade: 'UND' },
  { id: 51718, nome: 'CANETA ESFEROGRÁFICA AZUL', unidade: 'UND' },
  { id: 51717, nome: 'CANETA ESFEROGRÁFICA PRETA', unidade: 'UND' },
  { id: 51719, nome: 'CANETA ESFEROGRÁFICA VERMELHA', unidade: 'UND' },
  { id: 6898, nome: 'CANETA HIDROGRAFICA 12 CORES', unidade: 'UND' },
  { id: 53184, nome: 'CANETA MARCADOR PERMANENTE AZUL', unidade: 'UND' },
  { id: 53185, nome: 'CANETA MARCADOR PERMANENTE PRETA', unidade: 'UND' },
  { id: 53186, nome: 'CANETA MARCADOR PERMANENTE VERMELHO', unidade: 'UND' },
  { id: 6895, nome: 'CARIMBO AUTO-ENTITADO', unidade: 'UND' },
  { id: 1444, nome: 'CLIPS PARA PAPÉIS N° 2/0', unidade: 'CX' },
  { id: 52189, nome: 'CLIPS PARA PAPÉIS N° 4/0', unidade: 'CX' },
  { id: 51747, nome: 'CLIPS PARA PAPÉIS N° 6/0', unidade: 'CX' },
  { id: 51745, nome: 'CLIPS PARA PAPÉIS N° 8/0', unidade: 'CX' },
  { id: 52192, nome: 'CLIPS TRANÇADO', unidade: 'CX' },
  { id: 55245, nome: 'COLA LÍQUIDA BRANCA 90 GRAMAS LAVÁVEL', unidade: 'UND' },
  { id: 53176, nome: 'CORRETIVO CANETA', unidade: 'UND' },
  { id: 53175, nome: 'CORRETIVO EM FITA', unidade: 'CX' },
  { id: 55219, nome: 'ELÁSTICO DE BORRACHA', unidade: 'CX' },
  { id: 55237, nome: 'ENVELOPE PARDO – A4', unidade: 'UND' },
  { id: 52210, nome: 'ENVELOPE PARDO 200X280', unidade: 'UND' },
  { id: 52211, nome: 'ENVELOPE PARDO 260X360', unidade: 'UND' },
  { id: 55238, nome: 'ENVELOPE PARDO 310X410', unidade: 'UND' },
  { id: 55227, nome: 'ESTILETE', unidade: 'UND' },
  { id: 55086, nome: 'ETIQUETA A4 – MÉDIA: ETIQUETA BRANCA, 10 ETIQUETAS POR FOLHA, 25 FOLHAS, MEDIDA: 101,6MM X 50,8MM', unidade: 'CX' },
  { id: 55087, nome: 'ETIQUETA A4 – PEQUENA: ETIQUETA BRANCA, 60 ETIQUETAS POR FOLHA, 25 FOLHAS, MEDIDA: 44,45MM X 16,93MM', unidade: 'CX' },
  { id: 55224, nome: 'EXTRATOR DE GRAMPOS', unidade: 'UND' },
  { id: 51733, nome: 'FITA ADESIVA TRANSPARENTE 12X30', unidade: 'UND' },
  { id: 23702, nome: 'FITA ADESIVA TRANSPARENTE 50X50', unidade: 'UND' },
  { id: 51734, nome: 'FITA CREPE ADESIVA 48X50', unidade: 'UND' },
  { id: 52182, nome: 'GIZ DE CERA', unidade: 'UND' },
  { id: 49997, nome: 'GRAMPEADOR MÉDIO DE MESA METÁLICO', unidade: 'UND' },
  { id: 55226, nome: 'GRAMPO PARA GRAMPEADOR 26/6', unidade: 'CX' },
  { id: 52198, nome: 'GRAMPO TRILHO METÁLICO – ROMEU E JULIETA', unidade: 'CX' },
  { id: 52199, nome: 'GRAMPO TRILHO PLÁSTICO – ROMEU E JULIETA', unidade: 'CX' },
  { id: 6910, nome: 'LÁPIS DE COR 12 CORES', unidade: 'CX' },
  { id: 55244, nome: 'LÁPIS PRETO Nº 02: TRADICIONAL', unidade: 'UND' },
  { id: 55235, nome: 'LIVRO ATA', unidade: 'UND' },
  { id: 55236, nome: 'LIVRO DE PROTOCOLO', unidade: 'UND' },
  { id: 51753, nome: 'MARCA TEXTO', unidade: 'UND' },
  { id: 54580, nome: 'MARCADOR DE PÁGINA ADESIVO', unidade: 'UND' },
  { id: 55221, nome: 'ORGANIZADOR PORTA LÁPIS/CLIPS/LEMBRETE', unidade: 'UND' },
  { id: 37484, nome: 'ORGANIZADOR TRIPLO DE MESA – CRISTAL', unidade: 'UND' },
  { id: 52212, nome: 'PASTA AZ: TAMANHO A4 (320X290X75MM)', unidade: 'UND' },
  { id: 55241, nome: 'PASTA CATÁLOGO: C/ 100 FOLHAS PLÁSTICAS', unidade: 'UND' },
  { id: 51724, nome: 'PASTA CORRUGADA', unidade: 'UND' },
  { id: 55240, nome: 'PASTA CORRUGADA – CRISTAL', unidade: 'UND' },
  { id: 55242, nome: 'PASTA L', unidade: 'UND' },
  { id: 50007, nome: 'PASTA SANFONADA C/ 31 DIVISÓRIAS', unidade: 'UND' },
  { id: 51722, nome: 'PASTA SUSPENSA KRAFT COMPLETA: COR PARDA', unidade: 'UND' },
  { id: 453, nome: 'PERCEVEJO', unidade: 'CX' },
  { id: 15537, nome: 'PERFURADOR DE PAPEL: 2 FUROS', unidade: 'UND' },
  { id: 55231, nome: 'PILHA AA: PILHA ALCALINA PEQUENA, MODELO AA', unidade: 'UND' },
  { id: 55232, nome: 'PILHA AAA: PILHA ALCALINA PALITO, MODELO AAA', unidade: 'UND' },
  { id: 52207, nome: 'PILHA C: PILHA ALCALINA MÉDIA, MODELO C', unidade: 'UND' },
  { id: 52186, nome: 'PINCEL PARA QUADRO BRANCO – AZUL', unidade: 'UND' },
  { id: 52187, nome: 'PINCEL PARA QUADRO BRANCO – PRETO', unidade: 'UND' },
  { id: 52188, nome: 'PINCEL PARA QUADRO BRANCO – VERMELHO', unidade: 'UND' },
  { id: 55230, nome: 'PRANCHETA EM MDF, EUCATEX ACRÍLICO', unidade: 'UND' },
  { id: 55220, nome: 'RÉGUA DE ACRÍLICO TRANSPARENTE 30 CM', unidade: 'UND' },
  { id: 52213, nome: 'SACO PLÁSTICO TRANSPARENTE 4 FUROS - A4', unidade: 'UND' },
  { id: 51750, nome: 'SULFITE A4', unidade: 'RES' },
  { id: 55228, nome: 'TESOURA ESCOLAR: AÇO INOX, 13 CM', unidade: 'UND' },
  { id: 55229, nome: 'TESOURA GRANDE 21 CM', unidade: 'UND' },
  { id: 385, nome: 'TINTA PARA CARIMBO NA COR AZUL', unidade: 'UND' },
  { id: 55223, nome: 'TINTA PARA CARIMBO NA COR PRETA', unidade: 'UND' },
  { id: 51762, nome: 'TINTA PARA CARIMBO NA COR VERMELHA', unidade: 'UND' },
  { id: 51738, nome: 'UMEDECEDOR DE DEDOS', unidade: 'UND' }
];