// src/app/pedidos/produtos.js

export const LISTA_LIMPEZA = [
  { id: '55093', nome: 'ÁGUA SANITÁRIA (FRASCO C/ 5 L)', unidade: 'UND' },
  { id: '51685', nome: 'ÁLCOOL ETÍLICO 70% C/ 1 LITRO', unidade: 'UND' },
  { id: '52618', nome: 'ÁLCOOL EM GEL – GALÃO DE 5 LITROS', unidade: 'UND' },
  { id: '50040', nome: 'BALDE DE POLIETILENO CAPACIDADE DE 20 LITROS, ALÇA DE METAL', unidade: 'UND' },
  { id: '52614', nome: 'BALDE DE POLIETILENO CAPACIDADE DE 30 LITROS, ALÇA DE METAL', unidade: 'UND' },
  { id: '51524', nome: 'BALDE ESPREMEDOR P/ LIMPEZA; CONJUNTO DE BALDE E ESPREMEDOR', unidade: 'UND' },
  { id: '51523', nome: 'CABELEIRA DE ALGODÃO - (REFIL MOP) BRANCO', unidade: 'UND' },
  { id: '55097', nome: 'CERA LÍQUIDA PARA PISO', unidade: 'UND' },
  { id: '51533', nome: 'CESTO DE LIXO S/ TAMPA 12 LITROS', unidade: 'UND' },
  { id: '52612', nome: 'CONJUNTO DE MANGUEIRA – 30M', unidade: 'UND' },
  { id: '51509', nome: 'COPO DESCARTÁVEL PARA ÁGUA 200 ML', unidade: 'PCT' },
  { id: '51510', nome: 'COPO DESCARTÁVEL PARA CAFÉ 50 ML', unidade: 'PCT' },
  { id: '51662', nome: 'DESINFETANTE DESODORIZANTE DE USO GERAL - FRASCO COM 2 LITROS', unidade: 'UND' },
  { id: '51548', nome: 'DETERGENTE LÍQUIDO NEUTRO (FRASCO C/ 500 ML)', unidade: 'UND' },
  { id: '51542', nome: 'DISPENSER DE COPO DE ÁGUA – 180 / 200 ML', unidade: 'UND' },
  { id: '51541', nome: 'DISPENSER DE PAPEL HIGIÊNICO', unidade: 'UND' },
  { id: '51540', nome: 'DISPENSER DE PAPEL TOALHA', unidade: 'UND' },
  { id: '51539', nome: 'DISPENSER DE SABÃO LÍQUIDO', unidade: 'UND' },
  { id: '54742', nome: 'ESCOVA DE LIMPEZA CANTOS', unidade: 'UND' },
  { id: '51527', nome: 'ESCOVA DE LIMPEZA MULTI-USO', unidade: 'UND' },
  { id: '50043', nome: 'ESFREGÃO; ÚMIDO COM CABELEIRA DE ALGODÃO', unidade: 'UND' },
  { id: '51529', nome: 'ESPONJA DE AÇO', unidade: 'PCT' },
  { id: '51530', nome: 'ESPONJA DUPLA FACE MULTIUSO', unidade: 'UND' },
  { id: '52609', nome: 'FIBRA DE LIMPEZA - VERDE', unidade: 'UND' },
  { id: '54804', nome: 'FILTRO DE PAPEL Nº 102', unidade: 'CX' },
  { id: '51531', nome: 'FLANELA COM BORDAS OVERLOQUEADAS', unidade: 'UND' },
  { id: '54739', nome: 'LIMPADOR MULTIUSO', unidade: 'UND' },
  { id: '51538', nome: 'LIXEIRA 100 LITROS', unidade: 'UND' },
  { id: '51535', nome: 'LIXEIRA 20 LITROS', unidade: 'UND' },
  { id: '51536', nome: 'LIXEIRA 50 LITROS', unidade: 'UND' },
  { id: '51522', nome: 'LUVA DE BORRACHA PARA LIMPEZA G (Nº9)', unidade: 'UND' },
  { id: '51521', nome: 'LUVA DE BORRACHA PARA LIMPEZA M (Nº8)', unidade: 'UND' },
  { id: '51520', nome: 'LUVA DE BORRACHA PARA LIMPEZA P (Nº7)', unidade: 'UND' },
  { id: '51526', nome: 'PÁ DE LIXO COM CABO LONGO EM PLÁSTICO', unidade: 'UND' },
  { id: '51528', nome: 'PANO DE CHÃO ALVEJADO - TIPO SACO', unidade: 'UND' },
  { id: '52613', nome: 'PANO MULTI-USO', unidade: 'ROL' },
  { id: '51513', nome: 'PAPEL HIGIÊNICO BRANCO INSTITUCIONAL', unidade: 'UND' },
  { id: '51512', nome: 'PAPEL HIGIÊNICO PCT 4 ROLOS, DE COR BRANCA', unidade: 'PCT' },
  { id: '51514', nome: 'PAPEL TOALHA INTERFOLHA', unidade: 'PCT' },
  { id: '55098', nome: 'POLIDOR DE MÓVEIS - FRASCO COM 200 ML', unidade: 'UND' },
  { id: '50039', nome: 'RODO DE MADEIRA COM CABO - 40 CM', unidade: 'UND' },
  { id: '52610', nome: 'RODO DE MADEIRA COM CABO - 60 CM', unidade: 'UND' },
  { id: '51551', nome: 'SABÃO EM BARRA COMUM - 200 GR', unidade: 'UND' },
  { id: '55094', nome: 'SABÃO EM BARRA, DE COCO - 200 GR', unidade: 'UND' },
  { id: '55095', nome: 'SABÃO EM PÓ – EMBALAGEM 1 KG', unidade: 'UND' },
  { id: '55091', nome: 'SABONETE LÍQUIDO - GALÃO DE 5 LITROS', unidade: 'UND' },
  { id: '52601', nome: 'SACO DE LIXO 110 LITROS – COR PRETO', unidade: 'UND' },
  { id: '51516', nome: 'SACO DE LIXO PRETO MEDINDO 59X62, 30 LITROS', unidade: 'PCT' },
  { id: '51518', nome: 'SACO DE LIXO PRETO MEDINDO 65X100, 60 LITROS', unidade: 'PCT' },
  { id: '51519', nome: 'SACO DE LIXO PRETO MEDINDO 80X100, 100 LITROS', unidade: 'PCT' },
  { id: '54813', nome: 'SAPONÁCEO CREMOSO MULTIUSO - EMBALAGEM COM NO MÍNIMO 250ML', unidade: 'UND' },
  { id: '55096', nome: 'SAPONÁCEO EM PÓ COM DETERGENTE, EM FRASCO DE 300GR', unidade: 'UND' },
  { id: '52616', nome: 'VARAL DE CHÃO', unidade: 'UND' },
  { id: '37855', nome: 'VASSOURA DE NYLON PARA LIMPEZA DE VASO SANITÁRIO', unidade: 'UND' },
  { id: '8894', nome: 'VASSOURA DE PELO COM CABO - 30 CM', unidade: 'UND' },
  { id: '51525', nome: 'VASSOURA DE PIAÇAVA COM CABO - 40 CM', unidade: 'UND' }
];